name: End-to-end tests
on: [push, pull_request]
jobs:
  tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    timeout-minutes: 15
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        adapter: ['vue3']
        browser: ['chrome']
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build Inertia
        run: |
          pnpm install
          cd packages/core && pnpm run build
          cd ../vue3 && pnpm run build

      - name: Install Cypress Dependencies
        run: |
          cd packages/${{ matrix.adapter }}/tests
          pnpm install
          pnpm link "@inertiajs/core" "@inertiajs/${{ matrix.adapter }}"

      - name: Run Cypress (${{ matrix.browser }} / ${{ matrix.adapter }})
        run: |
          cd packages/${{ matrix.adapter }}/tests
          pnpm run ci